# Config ------------------------------------------------------------------------------------------
[Mods.PboneUtils.Config]
Header.ItemToggles = "Item Toggles"

Option.ItemToggle_LiquidItems.Label = "Liquid Items"
Option.ItemToggle_LiquidItems.Tooltip = "Enable or disable this mod's liquid items, which let you place and absorb infinite amounts of lava or honey"